import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
    opacity: 0.59,
  },
  safeArea: {
    flex: 1,
  },
  resultCard: {
    marginHorizontal: 24,
    marginBottom: 24,
    backgroundColor: colors.cardBackground,
    borderRadius: 24,
    padding: 20,
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 21.3,
    elevation: 8,
    opacity: 0.9,
  },
  resultCardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 8,
  },
  resultCardValue: {
    fontSize: 36,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 4,
  },
  resultCardFormula: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  mainCard: {
    flex: 1,
    backgroundColor: colors.cardBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 100,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -24 },
    shadowOpacity: 1,
    shadowRadius: 1,
    elevation: 24,
    opacity: 0.9,
  },
  sectionCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 4.8,
    elevation: 3,
    opacity: 0.9,
  },
  sectionCardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 16,
  },
  weightInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: 13,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  weightInput: {
    flex: 1,
    fontSize: 16,
    color: colors.textDark,
    height: 48,
  },
  weightUnit: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textMuted,
  },
  activityOption: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
  },
  activityOptionBorder: {
    borderTopWidth: 1,
    borderTopColor: colors.inputBackground,
  },
  radioOuter: {
    width: 17,
    height: 17,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 3,
    marginRight: 14,
  },
  radioInner: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  activityOptionContent: {
    flex: 1,
  },
  activityOptionTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.textDark,
    marginBottom: 2,
  },
  activityOptionSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
  },
});
